[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"

[target.'cfg(target_arch = "aarch64")'] 
rustflags = ["-C", "target-feature=+neon"]

[target.'cfg(target_arch = "x86_64")'] 
rustflags = ["-C", "target-feature=+avx2,+fma"]
